name = "3DEN Attributes Fast Load"
prefix = "3den_attributes_fast_laod"
author = "Brett Mayson"
mainprefix = "a3"

[version]
git_hash = 0 # Disabled
major = 1
minor = 0
patch = 0

[hemtt.launch.default]
workshop = [
    "2871002081"
]
